sudo: required                                     

language: c

before_install:
  ## PPA for Rcpp and some other packages
  - sudo add-apt-repository -y ppa:edd/misc
  ## r-travis by Craig Citro et al
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  
script: 
  - ./travis-tool.sh run_tests