language: c

sudo: required

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - RunAllRcppTests="yes"
    - CRAN="http://cran.us.r-project.org"

before_install:
  ## PPA for Rcpp and some other packages
  - sudo add-apt-repository -y ppa:edd/misc
  - sudo apt-get update -q
  ## r-travis by Craig Citro et al
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  
script: 
  - ./travis-tool.sh run_tests